const DeptMapping = {
    "AFR": "African Studies",
    "ANA": "Anatomy",
    "ANT": "Anthropology",
    "ARCLA": "Architectural Studies",
    "AST": "Astronomy and Astrophysics",
    "BCH": "Biochemistry",
    "CCS": "Caribbean Studies",
    "CERES": "European, Russian, and Eurasian Studies",
    "CHM": "Chemistry",
    "CINE": "Cinema Studies",
    "CLAS": "Classics",
    "CRIM": "Criminology",
    "CSB": "Cell and Systems Biology",
    "CSC": "Computer Science",
    "CSUS": "Canadian Studies",
    "DRAMA": "Drama, Theatre and Performance Studies",
    "EAS": "East Asian Studies",
    "ECO": "Economics",
    "EEB": "Ecology and Evolutionary Biology",
    "ENG": "English",
    "ENT": "Entomology",
    "ENVMT": "Environment / Environmental Studies",
    "ES": "Earth Sciences",
    "ETHIC": "Ethics",
    "FAR": "Fine Art History",
    "FOR": "Forestry",
    "FRE": "French",
    "GER": "German",
    "GGR": "Geography",
    "GLAF": "Global Affairs",
    "GLG": "Geology",
    "HIS": "History",
    "HMB": "Human Biology",
    "IHPST": "History and Philosophy of Science and Technology",
    "IMM": "Immunology",
    "INNIS": "Innis College",
    "IRE": "Industrial Relations",
    "ITA": "Italian",
    "JSP": "Jewish Studies",
    "LAS": "Latin American Studies",
    "LIN": "Linguistics",
    "LMP": "Laboratory Medicine and Pathobiology",
    "MAT": "Mathematics",
    "MEDGM": "Medical Genomics",
    "MST": "Medieval Studies",
    "MUSIC": "Music",
    "NEW": "New College",
    "NMC": "Near and Middle Eastern Civilizations",
    "NUSCI": "Nutritional Sciences",
    "OISUT": "OISE Undergraduate Teaching",
    "OTC": "Orthodox Theology / Old Testament Studies",
    "PCL": "Pharmacology",
    "PHL": "Philosophy",
    "PHM": "Pharmacy",
    "PHY": "Physics",
    "POL": "Political Science",
    "PSL": "Physiology",
    "PSY": "Psychology",
    "RLG": "Religion",
    "SAS": "South Asian Studies",
    "SDST": "Sexual Diversity Studies",
    "SLA": "Slavic Languages and Literatures",
    "SMC": "St. Michael's College",
    "SOC": "Sociology",
    "SPA": "Spanish",
    "SPP": "School of Public Policy and Governance",
    "STAT": "Statistical Sciences",
    "TRIN": "Trinity College",
    "UC": "University College",
    "VIC": "Victoria College",
    "WDW": "Woodsworth College",
    "WGSI": "Women and Gender Studies Institute",
    "ASDN": "Big Ideas",
    "DTS": "Diaspora & Transnational Studies",
    "CFE": "Environment",
    "ASABS": "Indigenous Studies",
}